#cspoo_swiftmailer_mailgun:
    #key: '%env(MAILGUN_API_KEY)%'
    #domain: "%env(MAILGUN_DOMAIN)%"

#services:
    #Mailgun\Mailgun:
        #class: Mailgun\Mailgun
        #factory: ['Mailgun\Mailgun', create]
        #arguments: ['%env(MAILGUN_API_KEY)%']
