sonata_seo:
    encoding:         UTF-8
    page:
        title:            My Best Quotes 
        default:          sonata.seo.page.default
        separator:        ' - '
        metas:
            name:
                keywords:             quotes, best quotes,My Best Quotes
                description:          Y BEST QUOTES -myquotes.be | Best myquote Quotes, Status, Shayari, Poetry Quotes can be inspirational and motivational. Enjoy a wallpaper image of a new inspirational quote  | MyQuote.
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       My Best Quotes 
                'og:description':     Y BEST QUOTES -myquotes.be | Best myquote Quotes, Status, Shayari, Poetry Quotes can be inspirational and motivational. Enjoy a wallpaper image of a new inspirational quote  | MyQuote.

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"