easy_admin:
    entities:
        Role:
            class: App\Entity\Role
            label: 'Roles'
            list:
                fields:
                    - { property: 'users' }
                    - { property: 'title', }
            show:
                fields:
                    - { property: 'users' }
                    - { property: 'title', type: 'choice', type_options: {  choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'Basic information', icon: 'pencil' }
                    - { property: 'users' }
                    - { property: 'title'}
